# Generated by Django 4.2.6 on 2023-12-16 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_gas_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='electric_supplier_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.electric_supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='gas_supplier_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.gas_supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='water_supplier_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.water_supplier'),
            preserve_default=False,
        ),
    ]
