version: '3.4'

services:
  ui:
    image: ui
    build:
      context: front-end/ui
      dockerfile: ./Dockerfile-ui
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    stdin_open: true
    tty: true

  django-api:
    build:
      context: back_end
      dockerfile: ./Dockerfile-api
    ports:
      - 8000:8000
