# Generated by Django 4.2.6 on 2023-10-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('bank_sort_code', models.CharField(max_length=8)),
                ('bank_account_number', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=10)),
                ('current_value', models.FloatField()),
                ('epc_renewal_date', models.DateField()),
                ('gas_certificate_renewal_date', models.DateField()),
                ('electrical_inspection_date', models.DateField()),
                ('gas_supplier', models.CharField(max_length=20)),
                ('electric_supplier', models.CharField(max_length=20)),
                ('water_supplier', models.CharField(max_length=20)),
                ('entry_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('bank_sort_code', models.CharField(max_length=8)),
                ('bank_account_number', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField()),
                ('initial_rent_amount', models.FloatField()),
                ('final_rent_amount', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('contract_term', models.PositiveIntegerField()),
                ('initial_rent_amount', models.FloatField()),
                ('current_rent_amount', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('rent_review_date', models.DateField()),
                ('deposit_amount', models.FloatField()),
                ('deposit_lodged_with_dps', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('purchase_method', models.CharField(max_length=20)),
                ('purchase_type', models.CharField(max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='current_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('amount_borrowed', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('term', models.PositiveIntegerField()),
                ('lender_name', models.CharField(max_length=20)),
                ('lender_address', models.TextField()),
                ('lender_email', models.EmailField(max_length=254)),
                ('lender_phone_number', models.CharField(max_length=13)),
                ('mortgage_type', models.CharField(max_length=20)),
                ('monthly_amount', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('date_reported', models.DateField()),
                ('date_fixed', models.DateField()),
                ('contractor_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractor')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_number', models.CharField(max_length=20)),
                ('premium', models.FloatField()),
                ('renewal_due', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Gas_Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(max_length=20)),
                ('reading_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Electric_Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(max_length=20)),
                ('reading_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
    ]
