# Generated by Django 4.2.6 on 2023-11-01 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agent_property_council_license_renewal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='renewal_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
