# Generated by Django 4.2.6 on 2023-11-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mortgage_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='company',
            field=models.CharField(default='Mors mutual', max_length=30),
            preserve_default=False,
        ),
    ]
