# Generated by Django 4.2.6 on 2023-12-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_electric_reading_tenant_gas_reading_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ast_url', models.TextField()),
                ('epc_url', models.TextField()),
                ('electrical_cert_url', models.TextField()),
                ('gas_safety_url', models.TextField()),
                ('inventory_url', models.TextField()),
                ('other_docs_url', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
    ]
