# Generated by Django 4.2.6 on 2023-12-16 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit_scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=50)),
                ('scheme_contact_number', models.CharField(max_length=13)),
                ('scheme_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.TextField(default='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='previous_premium',
            field=models.FloatField(default=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenancy',
            name='scheme_policy_number',
            field=models.CharField(default='12345', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_name',
            field=models.CharField(default='Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_phone_number',
            field=models.CharField(default='1234457888', max_length=13),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AgentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
    ]
