# Generated by Django 4.2.6 on 2023-12-16 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_deposit_scheme_agent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='scheme_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.deposit_scheme'),
            preserve_default=False,
        ),
    ]
