# Generated by Django 4.2.6 on 2023-12-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_gas_electric_supplier_water_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gas_Electric_Supplier',
            new_name='Electric_Supplier',
        ),
        migrations.RemoveField(
            model_name='property',
            name='electric_supplier',
        ),
        migrations.RemoveField(
            model_name='property',
            name='gas_supplier',
        ),
        migrations.RemoveField(
            model_name='property',
            name='water_supplier',
        ),
    ]
