# Generated by Django 4.2.6 on 2023-12-16 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_property_electric_supplier_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenthistory',
            name='start_date',
        ),
        migrations.AddField(
            model_name='agent',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
