# Generated by Django 4.2.6 on 2024-01-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_agenthistory_start_date_agent_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_scheme',
            name='scheme_address',
            field=models.CharField(default='address1', max_length=50),
            preserve_default=False,
        ),
    ]
