# Generated by Django 4.2.6 on 2024-01-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_deposit_scheme_scheme_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit_scheme',
            name='scheme_address',
        ),
    ]
