# Generated by Django 4.2.6 on 2024-01-06 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_deposit_scheme_scheme_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='start_date',
        ),
        migrations.AddField(
            model_name='property',
            name='agent_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
