# Generated by Django 4.2.6 on 2024-01-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_electric_reading_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gas_reading',
            name='reading',
        ),
    ]
