# Generated by Django 4.2.6 on 2024-01-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_gas_reading_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gas_reading',
            name='reading_date',
        ),
    ]
