# Generated by Django 4.2.6 on 2024-02-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_council_license_renewal_date_property_council_license_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='payment_method',
            field=models.CharField(max_length=16),
        ),
    ]
