# Generated by Django 4.2.6 on 2024-02-28 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_agent_address_alter_agent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='company',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='premium',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='previous_premium',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='renewal_due',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='amount_borrowed',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='interest_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='lender_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='lender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='lender_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='lender_phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='monthly_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='mortgage_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='renewal_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='term',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent_start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='council_license_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='current_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='electric_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='electric_supplier_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.electric_supplier'),
        ),
        migrations.AlterField(
            model_name='property',
            name='electrical_inspection_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='entry_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='epc_renewal_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gas_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='gas_certificate_renewal_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gas_supplier_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gas_supplier'),
        ),
        migrations.AlterField(
            model_name='property',
            name='water_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='water_supplier_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.water_supplier'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='purchase_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='purchase_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='purchase_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='purchase_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='amount_paid',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='contract_term',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='current_rent_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='deposit_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='deposit_lodged_with_dps',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='initial_rent_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='move_in_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='payment_method',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='rent_review_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='scheme_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deposit_scheme'),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='scheme_policy_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='tenancy_renewal_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='ast_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='electrical_cert_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='epc_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='gas_safety_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='inventory_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='other_docs_url',
            field=models.TextField(blank=True),
        ),
    ]
