# Generated by Django 4.2.6 on 2024-02-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_property_agent_alter_property_agent_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='premium',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='previous_premium',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='renewal_due',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='amount_borrowed',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='interest_rate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='monthly_amount',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='renewal_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='term',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent_start_date',
            field=models.CharField(blank=True, default='2000-01-02', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='council_license_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='electrical_inspection_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='epc_renewal_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='gas_certificate_renewal_date',
            field=models.CharField(blank=True, default='2000-02-02', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='purchase_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='contract_term',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='current_rent_amount',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='deposit_amount',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='initial_rent_amount',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='move_in_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='rent_review_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='scheme_name',
            field=models.CharField(blank=True, default='2000-02-02', max_length=50),
            preserve_default=False,
        ),
    ]
