# Generated by Django 4.2.6 on 2024-02-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_insurance_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='scheme_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='tenancy_renewal_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
