# Generated by Django 4.2.6 on 2024-02-29 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_tenancy_scheme_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='current_tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.tenant'),
            preserve_default=False,
        ),
    ]
