# Generated by Django 4.2.6 on 2024-02-29 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_property_current_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='current_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.tenant'),
        ),
    ]
