# Generated by Django 4.2.6 on 2024-03-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_tenant_email_2_tenant_phone_number_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
