# Generated by Django 4.2.6 on 2024-03-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
