# Generated by Django 4.2.6 on 2024-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_mortgage_lender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='company_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='insurance',
            name='company_email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='insurance',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
