# Generated by Django 4.2.6 on 2024-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_insurance_company_address_insurance_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='company_email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
