# Generated by Django 4.2.6 on 2024-04-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_insurance_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='start_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
