# Generated by Django 4.2.6 on 2024-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_mortgage_start_date_tenant_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_scheme',
            name='scheme_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='electric_supplier',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gas_supplier',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='water_supplier',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
