# Generated by Django 4.2.6 on 2024-04-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_deposit_scheme_scheme_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='contractor_responsible',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.contractor'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='date_reported',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='problem',
            field=models.TextField(blank=True),
        ),
    ]
