# Generated by Django 4.2.6 on 2024-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_issues_contractor_responsible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='date_fixed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='date_reported',
            field=models.TextField(blank=True),
        ),
    ]
