# Generated by Django 4.2.6 on 2024-04-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_issues_date_fixed_alter_issues_date_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='contractor_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contractor'),
        ),
    ]
