# Generated by Django 4.2.6 on 2024-04-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_issues_contractor_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='contractor_responsible',
            field=models.TextField(blank=True),
        ),
    ]
