# Generated by Django 4.2.6 on 2024-05-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_trade_supplier_issues_date_allocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(blank=True)),
                ('date', models.TextField(blank=True)),
                ('date_allocated', models.TextField(blank=True)),
                ('cost', models.TextField(blank=True)),
                ('contractor_responsible', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
    ]
