# Generated by Django 4.2.6 on 2024-05-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='contractor_responsible',
            new_name='trade_supplier',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='date_allocated',
        ),
    ]
